# permissions for end users to edit clustercredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercredential-editor-role
rules:
- apiGroups:
  - platform.tkestack.io
  resources:
  - clustercredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.tkestack.io
  resources:
  - clustercredentials/status
  verbs:
  - get
