# permissions for end users to view clustercredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercredential-viewer-role
rules:
- apiGroups:
  - platform.tkestack.io
  resources:
  - clustercredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.tkestack.io
  resources:
  - clustercredentials/status
  verbs:
  - get
